### ISSUE TITLE
BSD or GPL license?

### ISSUE THREAD

**Issue by wildfiremedia** [Ben-G/DataRaceDetector#1]
http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/35604.pdf
References [7] in the article indicated GPL:
The source code of ThreadSanitizer is published under the
GPL license and can be downloaded at [7].

BSD License
https://code.google.com/archive/p/data-race-test/

Which should I follow?

**Comment by Ben-G** [comment]
@wildfiremedia Hey! I can't comment on the licensing of Google's source code. However, this repo is based on the ideas discussed in the paper not on the original source code and it's licensed under the MIT license.

Hope this answers your question; if not, I'll reopen the issue!
